# -*- coding: utf-8 -*-
"""read_s3_data_sagemaker_template.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tlvnaFU_ZEc1lvZVDHlOk0rUP5miLmr0

Michael McCarthy mbmccart@utica.edu

MIT License
"""

# Commented out IPython magic to ensure Python compatibility.

# %pip install pandas 
# %pip install sagemaker
# %pip install researchpy
print("done")

# Commented out IPython magic to ensure Python compatibility.
#/opt/conda/bin/python 
-m pip install --upgrade pip
# %pip install boto3
print("done")

# https://www.stackvidhya.com/load-data-from-aws-s3-into-sagemaker/
#SCROLL TO: "Loading CSV File From S3 Bucket Using Boto3"
import pandas as pd
import boto3            #for S3 data import
import sagemaker
import io
import researchpy as rp #for descriptive Stats
import time
print("done")

#inport Data from Bucket with file name = file_key
bucket='bucket-name'
file_key = 'filename.xlsx' #note, this is xlsx....update below if csv

s3_client = boto3.client('s3')
obj = s3_client.get_object(Bucket=bucket, Key=file_key)
#The pd.read_____ will be excel or csv be sure to update
df = pd.read_excel(io.BytesIO(obj['Body'].read())) #update if csv
df.head()
print("done &\ndone")